const responseMockFetchItems = {
  site_id: "MLA",
  country_default_time_zone: "GMT-03:00",
  query: "pelota",
  paging: {
    total: 41799,
    primary_results: 1000,
    offset: 0,
    limit: 50,
  },
  results: [
    {
      id: "MLA629108518",
      title:
        "Pelota De Pilates 24 Cm Lisa Sin Peso Gmp - Pequeña - Para Gimnasia",
      condition: "new",
      thumbnail_id: "768836-MLA41305330298_042020",
      catalog_product_id: null,
      listing_type_id: "gold_special",
      permalink:
        "https://articulo.mercadolibre.com.ar/MLA-629108518-pelota-de-pilates-24-cm-lisa-sin-peso-gmp-pequena-para-gimnasia-_JM",
      buying_mode: "buy_it_now",
      site_id: "MLA",
      category_id: "MLA44774",
      domain_id: "MLA-PILATES_BALLS",
      thumbnail:
        "http://http2.mlstatic.com/D_768836-MLA41305330298_042020-I.jpg",
      currency_id: "ARS",
      order_backend: 1,
      price: 5695,
      original_price: null,
      sale_price: null,
      available_quantity: 250,
      official_store_id: 76622,
      official_store_name: "GMP",
      use_thumbnail_id: true,
      accepts_mercadopago: true,
      variation_filters: ["COLOR"],
      shipping: {
        store_pick_up: false,
        free_shipping: false,
        logistic_type: "fulfillment",
        mode: "me2",
        tags: ["fulfillment"],
        benefits: null,
        promise: null,
        shipping_score: -1,
      },
      stop_time: "2036-07-22T16:01:54.000Z",
      seller: {
        id: 838106,
        nickname: "GMP-EQUIPAMIENTOS",
      },
      attributes: [
        {
          id: "BRAND",
          name: "Marca",
          value_id: "3080134",
          value_name: "GMP",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "3080134",
              name: "GMP",
              struct: null,
              source: 2187367636293270,
            },
          ],
          source: 2187367636293270,
          value_type: "string",
        },
        {
          id: "ITEM_CONDITION",
          name: "Condición del ítem",
          value_id: "2230284",
          value_name: "Nuevo",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "2230284",
              name: "Nuevo",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "list",
        },
        {
          id: "MODEL",
          name: "Modelo",
          value_id: null,
          value_name: "24cm lisa",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: null,
              name: "24cm lisa",
              struct: null,
              source: 5033071320073938,
            },
          ],
          source: 5033071320073938,
          value_type: "string",
        },
        {
          id: "SALE_FORMAT",
          name: "Formato de venta",
          value_id: "1359391",
          value_name: "Unidad",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "1359391",
              name: "Unidad",
              struct: null,
              source: 7571550481372610,
            },
          ],
          source: 7571550481372610,
          value_type: "list",
        },
        {
          id: "UNITS_PER_PACK",
          name: "Unidades por pack",
          value_id: null,
          value_name: "1",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: null,
              name: "1",
              struct: null,
              source: 5033071320073938,
            },
          ],
          source: 5033071320073938,
          value_type: "number",
        },
      ],
      installments: {
        quantity: 6,
        amount: 1255.84,
        rate: 32.31,
        currency_id: "ARS",
      },
      winner_item_id: null,
      catalog_listing: false,
      discounts: null,
      promotions: [],
      inventory_id: null,
    },
    {
      id: "MLA1138677936",
      title: "Pelota Penalty Futbol Campo Bravo Original",
      condition: "new",
      thumbnail_id: "757768-MLA74433842726_022024",
      catalog_product_id: null,
      listing_type_id: "gold_special",
      permalink:
        "https://articulo.mercadolibre.com.ar/MLA-1138677936-pelota-penalty-futbol-campo-bravo-original-_JM",
      buying_mode: "buy_it_now",
      site_id: "MLA",
      category_id: "MLA1287",
      domain_id: "MLA-FOOTBALL_BALLS",
      thumbnail:
        "http://http2.mlstatic.com/D_757768-MLA74433842726_022024-I.jpg",
      currency_id: "ARS",
      order_backend: 46,
      price: 46897.7,
      original_price: 49366,
      sale_price: null,
      available_quantity: 50,
      official_store_id: null,
      use_thumbnail_id: true,
      accepts_mercadopago: true,
      variation_filters: ["COLOR"],
      shipping: {
        store_pick_up: false,
        free_shipping: true,
        logistic_type: "cross_docking",
        mode: "me2",
        tags: ["self_service_in", "mandatory_free_shipping"],
        benefits: null,
        promise: null,
        shipping_score: -1,
      },
      stop_time: "2042-05-18T04:00:00.000Z",
      seller: {
        id: 31719574,
        nickname: "LAVALLEDEPORTES",
      },
      attributes: [
        {
          id: "BRAND",
          name: "Marca",
          value_id: "415945",
          value_name: "Penalty",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "415945",
              name: "Penalty",
              struct: null,
              source: 6808261514773724,
            },
          ],
          source: 6808261514773724,
          value_type: "string",
        },
        {
          id: "ITEM_CONDITION",
          name: "Condición del ítem",
          value_id: "2230284",
          value_name: "Nuevo",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "2230284",
              name: "Nuevo",
              struct: null,
              source: 6808261514773724,
            },
          ],
          source: 6808261514773724,
          value_type: "list",
        },
        {
          id: "MODEL",
          name: "Modelo",
          value_id: "2987138",
          value_name: "Campo",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "2987138",
              name: "Campo",
              struct: null,
              source: 3942444344910321,
            },
          ],
          source: 3942444344910321,
          value_type: "string",
        },
        {
          id: "SALE_FORMAT",
          name: "Formato de venta",
          value_id: "1359391",
          value_name: "Unidad",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "1359391",
              name: "Unidad",
              struct: null,
              source: 3376461333454861,
            },
          ],
          source: 3376461333454861,
          value_type: "list",
        },
        {
          id: "UNITS_PER_PACK",
          name: "Unidades por pack",
          value_id: null,
          value_name: "1",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: null,
              name: "1",
              struct: null,
              source: 3376461333454861,
            },
          ],
          source: 3376461333454861,
          value_type: "number",
        },
      ],
      installments: {
        quantity: 6,
        amount: 10341.72,
        rate: 32.31,
        currency_id: "ARS",
      },
      winner_item_id: null,
      catalog_listing: false,
      discounts: null,
      promotions: [],
      inventory_id: null,
    },
    {
      id: "MLA1426958707",
      title:
        "Pelota Pilates Esferodinamia 65 Cm Gimnasia Yoga Relax Color Rosa",
      condition: "new",
      thumbnail_id: "638128-MLU76190048316_052024",
      catalog_product_id: "MLA36940629",
      listing_type_id: "gold_special",
      permalink:
        "https://www.mercadolibre.com.ar/pelota-pilates-esferodinamia-65-cm-gimnasia-yoga-relax-color-rosa/p/MLA36940629",
      buying_mode: "buy_it_now",
      site_id: "MLA",
      category_id: "MLA44774",
      domain_id: "MLA-PILATES_BALLS",
      thumbnail:
        "http://http2.mlstatic.com/D_638128-MLU76190048316_052024-I.jpg",
      currency_id: "ARS",
      order_backend: 47,
      price: 16130.63,
      original_price: null,
      sale_price: null,
      available_quantity: 1,
      official_store_id: null,
      use_thumbnail_id: true,
      accepts_mercadopago: true,
      shipping: {
        store_pick_up: false,
        free_shipping: false,
        logistic_type: "fulfillment",
        mode: "me2",
        tags: ["fulfillment", "self_service_out", "self_service_available"],
        benefits: null,
        promise: null,
        shipping_score: -1,
      },
      stop_time: "2044-05-11T04:00:00.000Z",
      seller: {
        id: 196606827,
        nickname: "MSALE300",
      },
      attributes: [
        {
          id: "BRAND",
          name: "Marca",
          value_id: "6630631",
          value_name: "Master Sale",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "6630631",
              name: "Master Sale",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "string",
        },
        {
          id: "COLOR",
          name: "Color",
          value_id: "51994",
          value_name: "Rosa",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "51994",
              name: "Rosa",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "string",
        },
        {
          id: "GTIN",
          name: "Código universal de producto",
          value_id: "-1",
          value_name: null,
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "-1",
              name: null,
              struct: null,
              source: 4333789534002961,
            },
          ],
          source: 4333789534002961,
          value_type: "string",
        },
        {
          id: "ITEM_CONDITION",
          name: "Condición del ítem",
          value_id: "2230284",
          value_name: "Nuevo",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "2230284",
              name: "Nuevo",
              struct: null,
              source: 6808261514773724,
            },
          ],
          source: 6808261514773724,
          value_type: "list",
        },
        {
          id: "MODEL",
          name: "Modelo",
          value_id: "4613223",
          value_name: "65 cm",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "4613223",
              name: "65 cm",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "string",
        },
        {
          id: "PACKAGE_LENGTH",
          name: "Largo del paquete",
          value_id: null,
          value_name: "15.2 cm",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: {
            number: 15.2,
            unit: "cm",
          },
          values: [
            {
              id: null,
              name: "15.2 cm",
              struct: {
                number: 15.2,
                unit: "cm",
              },
              source: 4333789534002961,
            },
          ],
          source: 4333789534002961,
          value_type: "number_unit",
        },
        {
          id: "PACKAGE_WEIGHT",
          name: "Peso del paquete",
          value_id: null,
          value_name: "800 g",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: {
            number: 800,
            unit: "g",
          },
          values: [
            {
              id: null,
              name: "800 g",
              struct: {
                number: 800,
                unit: "g",
              },
              source: 4333789534002961,
            },
          ],
          source: 4333789534002961,
          value_type: "number_unit",
        },
        {
          id: "UNITS_PER_PACK",
          name: "Unidades por pack",
          value_id: "2726554",
          value_name: "1",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "2726554",
              name: "1",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "number",
        },
      ],
      installments: {
        quantity: 6,
        amount: 3557.07,
        rate: 32.31,
        currency_id: "ARS",
      },
      winner_item_id: null,
      catalog_listing: true,
      discounts: null,
      promotions: [],
      inventory_id: "UTVK84933",
    },
    {
      id: "MLA1520712066",
      title: "Pelota De Futbol Numero 5 Nassau Spectro",
      condition: "new",
      thumbnail_id: "946103-MLU71251368655_082023",
      catalog_product_id: "MLA26320799",
      listing_type_id: "gold_special",
      permalink:
        "https://www.mercadolibre.com.ar/pelota-de-futbol-numero-5-nassau-spectro/p/MLA26320799",
      buying_mode: "buy_it_now",
      site_id: "MLA",
      category_id: "MLA1287",
      domain_id: "MLA-FOOTBALL_BALLS",
      thumbnail:
        "http://http2.mlstatic.com/D_946103-MLU71251368655_082023-I.jpg",
      currency_id: "ARS",
      order_backend: 48,
      price: 53750,
      original_price: null,
      sale_price: null,
      available_quantity: 1,
      official_store_id: null,
      use_thumbnail_id: true,
      accepts_mercadopago: true,
      shipping: {
        store_pick_up: false,
        free_shipping: true,
        logistic_type: "cross_docking",
        mode: "me2",
        tags: ["self_service_in", "mandatory_free_shipping"],
        benefits: null,
        promise: null,
        shipping_score: -1,
      },
      stop_time: "2043-09-22T04:00:00.000Z",
      seller: {
        id: 204978738,
        nickname: "WARRIORSDEPORTES",
      },
      attributes: [
        {
          id: "BRAND",
          name: "Marca",
          value_id: "3040564",
          value_name: "Nassau",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "3040564",
              name: "Nassau",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "string",
        },
        {
          id: "COLOR",
          name: "Color",
          value_id: "59793",
          value_name: "Blanco/Negro",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "59793",
              name: "Blanco/Negro",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "string",
        },
        {
          id: "GTIN",
          name: "Código universal de producto",
          value_id: null,
          value_name: "8804234001220",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: null,
              name: "8804234001220",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "string",
        },
        {
          id: "ITEM_CONDITION",
          name: "Condición del ítem",
          value_id: "2230284",
          value_name: "Nuevo",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "2230284",
              name: "Nuevo",
              struct: null,
              source: 3045741222775799,
            },
          ],
          source: 3045741222775799,
          value_type: "list",
        },
        {
          id: "MAIN_COLOR",
          name: "Color principal",
          value_id: "2450308",
          value_name: "Blanco",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "2450308",
              name: "Blanco",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "list",
        },
        {
          id: "MODEL",
          name: "Modelo",
          value_id: "235022",
          value_name: "Spectro",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "235022",
              name: "Spectro",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "string",
        },
        {
          id: "PACKAGE_LENGTH",
          name: "Largo del paquete",
          value_id: null,
          value_name: "20 cm",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: {
            number: 20,
            unit: "cm",
          },
          values: [
            {
              id: null,
              name: "20 cm",
              struct: {
                number: 20,
                unit: "cm",
              },
              source: 1,
            },
          ],
          source: 1,
          value_type: "number_unit",
        },
        {
          id: "PACKAGE_WEIGHT",
          name: "Peso del paquete",
          value_id: null,
          value_name: "420 g",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: {
            number: 420,
            unit: "g",
          },
          values: [
            {
              id: null,
              name: "420 g",
              struct: {
                number: 420,
                unit: "g",
              },
              source: 1,
            },
          ],
          source: 1,
          value_type: "number_unit",
        },
        {
          id: "SALE_FORMAT",
          name: "Formato de venta",
          value_id: "1359391",
          value_name: "Unidad",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "1359391",
              name: "Unidad",
              struct: null,
              source: 3045741222775799,
            },
          ],
          source: 3045741222775799,
          value_type: "list",
        },
        {
          id: "UNITS_PER_PACK",
          name: "Unidades por pack",
          value_id: "2726554",
          value_name: "1",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "2726554",
              name: "1",
              struct: null,
              source: 4709228965570453,
            },
          ],
          source: 4709228965570453,
          value_type: "number",
        },
      ],
      installments: {
        quantity: 6,
        amount: 11852.77,
        rate: 32.31,
        currency_id: "ARS",
      },
      winner_item_id: null,
      catalog_listing: true,
      discounts: null,
      promotions: [],
      inventory_id: "BUTL70735",
    },
    {
      id: "MLA1475947002",
      title: "Mini Compresor Inflador Cubiertas Auto Pelotas E Inflables",
      condition: "new",
      thumbnail_id: "854273-MLU73129697036_122023",
      catalog_product_id: "MLA22226600",
      listing_type_id: "gold_special",
      permalink:
        "https://www.mercadolibre.com.ar/mini-compresor-inflador-cubiertas-auto-pelotas-e-inflables/p/MLA22226600",
      buying_mode: "buy_it_now",
      site_id: "MLA",
      category_id: "MLA370796",
      domain_id: "MLA-AIR_COMPRESSORS",
      thumbnail:
        "http://http2.mlstatic.com/D_854273-MLU73129697036_122023-I.jpg",
      currency_id: "ARS",
      order_backend: 49,
      price: 34146.63,
      original_price: null,
      sale_price: null,
      available_quantity: 1,
      official_store_id: null,
      use_thumbnail_id: true,
      accepts_mercadopago: true,
      shipping: {
        store_pick_up: false,
        free_shipping: true,
        logistic_type: "fulfillment",
        mode: "me2",
        tags: ["fulfillment", "self_service_in", "mandatory_free_shipping"],
        benefits: null,
        promise: null,
        shipping_score: -1,
      },
      stop_time: "2043-08-13T04:00:00.000Z",
      seller: {
        id: 702150429,
        nickname: "GLOBALNAVET",
      },
      attributes: [
        {
          id: "AIR_COMPRESSOR_WEIGHT",
          name: "Peso del compresor de aire",
          value_id: "59112",
          value_name: "1 kg",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: {
            number: 1,
            unit: "kg",
          },
          values: [
            {
              id: "59112",
              name: "1 kg",
              struct: {
                number: 1,
                unit: "kg",
              },
              source: 1,
            },
          ],
          source: 1,
          value_type: "number_unit",
        },
        {
          id: "BRAND",
          name: "Marca",
          value_id: "2941475",
          value_name: "QKL",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "2941475",
              name: "QKL",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "string",
        },
        {
          id: "DETAILED_MODEL",
          name: "Modelo detallado",
          value_id: "17471684",
          value_name: "MC57",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "17471684",
              name: "MC57",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "string",
        },
        {
          id: "GTIN",
          name: "Código universal de producto",
          value_id: null,
          value_name: "7792993339757",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: null,
              name: "7792993339757",
              struct: null,
              source: 385122562515662,
            },
          ],
          source: 7567447101417086,
          value_type: "string",
        },
        {
          id: "HOSE_LENGTH",
          name: "Largo de la manguera",
          value_id: "8664151",
          value_name: "60 cm",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: {
            number: 60,
            unit: "cm",
          },
          values: [
            {
              id: "8664151",
              name: "60 cm",
              struct: {
                number: 60,
                unit: "cm",
              },
              source: 4709228965570453,
            },
          ],
          source: 4709228965570453,
          value_type: "number_unit",
        },
        {
          id: "ITEM_CONDITION",
          name: "Condición del ítem",
          value_id: "2230284",
          value_name: "Nuevo",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "2230284",
              name: "Nuevo",
              struct: null,
              source: 3045741222775799,
            },
          ],
          source: 3045741222775799,
          value_type: "list",
        },
        {
          id: "MODEL",
          name: "Modelo",
          value_id: "17471666",
          value_name: "mc57",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "17471666",
              name: "mc57",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "string",
        },
        {
          id: "PACKAGE_LENGTH",
          name: "Largo del paquete",
          value_id: null,
          value_name: "19 cm",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: {
            number: 19,
            unit: "cm",
          },
          values: [
            {
              id: null,
              name: "19 cm",
              struct: {
                number: 19,
                unit: "cm",
              },
              source: 4333789534002961,
            },
          ],
          source: 4333789534002961,
          value_type: "number_unit",
        },
        {
          id: "PACKAGE_WEIGHT",
          name: "Peso del paquete",
          value_id: null,
          value_name: "880 g",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: {
            number: 880,
            unit: "g",
          },
          values: [
            {
              id: null,
              name: "880 g",
              struct: {
                number: 880,
                unit: "g",
              },
              source: 4333789534002961,
            },
          ],
          source: 4333789534002961,
          value_type: "number_unit",
        },
        {
          id: "POWER",
          name: "Potencia",
          value_id: "107959",
          value_name: "180 W",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: {
            number: 180,
            unit: "W",
          },
          values: [
            {
              id: "107959",
              name: "180 W",
              struct: {
                unit: "W",
                number: 180,
              },
              source: 1,
            },
          ],
          source: 1,
          value_type: "number_unit",
        },
      ],
      installments: {
        quantity: 6,
        amount: 7529.9,
        rate: 32.31,
        currency_id: "ARS",
      },
      winner_item_id: null,
      catalog_listing: true,
      discounts: null,
      promotions: [],
      inventory_id: "BIXC71521",
    },
    {
      id: "MLA1824526484",
      title: "Pelota Munich N°5 Force Pu Match Ball Resistente Color Verde",
      condition: "new",
      thumbnail_id: "778470-MLU77244661737_062024",
      catalog_product_id: "MLA37887758",
      listing_type_id: "gold_special",
      permalink:
        "https://www.mercadolibre.com.ar/pelota-munich-n5-force-pu-match-ball-resistente-color-verde/p/MLA37887758",
      buying_mode: "buy_it_now",
      site_id: "MLA",
      category_id: "MLA1287",
      domain_id: "MLA-FOOTBALL_BALLS",
      thumbnail:
        "http://http2.mlstatic.com/D_778470-MLU77244661737_062024-I.jpg",
      currency_id: "ARS",
      order_backend: 50,
      price: 34403,
      original_price: null,
      sale_price: null,
      available_quantity: 1,
      official_store_id: null,
      use_thumbnail_id: true,
      accepts_mercadopago: true,
      shipping: {
        store_pick_up: false,
        free_shipping: true,
        logistic_type: "cross_docking",
        mode: "me2",
        tags: ["self_service_in", "mandatory_free_shipping"],
        benefits: null,
        promise: null,
        shipping_score: -1,
      },
      stop_time: "2044-06-21T04:00:00.000Z",
      seller: {
        id: 320182601,
        nickname: "MARATONURBANOOK",
      },
      attributes: [
        {
          id: "BRAND",
          name: "Marca",
          value_id: "526510",
          value_name: "Munich",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "526510",
              name: "Munich",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "string",
        },
        {
          id: "COLOR",
          name: "Color",
          value_id: "52014",
          value_name: "Verde",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "52014",
              name: "Verde",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "string",
        },
        {
          id: "FINISH",
          name: "Acabado",
          value_id: "2102514",
          value_name: "Brillante",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "2102514",
              name: "Brillante",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "string",
        },
        {
          id: "GTIN",
          name: "Código universal de producto",
          value_id: null,
          value_name: "5383672775052",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: null,
              name: "5383672775052",
              struct: null,
              source: 6402814585011704,
            },
          ],
          source: 6402814585011704,
          value_type: "string",
        },
        {
          id: "ITEM_CONDITION",
          name: "Condición del ítem",
          value_id: "2230284",
          value_name: "Nuevo",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "2230284",
              name: "Nuevo",
              struct: null,
              source: 6402814585011704,
            },
          ],
          source: 6402814585011704,
          value_type: "list",
        },
        {
          id: "MODEL",
          name: "Modelo",
          value_id: "139368",
          value_name: "Force",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "139368",
              name: "Force",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "string",
        },
        {
          id: "SALE_FORMAT",
          name: "Formato de venta",
          value_id: "1359391",
          value_name: "Unidad",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "1359391",
              name: "Unidad",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "list",
        },
        {
          id: "UNITS_PER_PACK",
          name: "Unidades por pack",
          value_id: "2726554",
          value_name: "1",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_struct: null,
          values: [
            {
              id: "2726554",
              name: "1",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_type: "number",
        },
      ],
      installments: {
        quantity: 6,
        amount: 7586.43,
        rate: 32.31,
        currency_id: "ARS",
      },
      winner_item_id: null,
      catalog_listing: true,
      discounts: null,
      promotions: [],
      inventory_id: null,
    },
  ],
  sort: {
    id: "relevance",
    name: "Más relevantes",
  },
  available_sorts: [
    {
      id: "price_asc",
      name: "Menor precio",
    },
    {
      id: "price_desc",
      name: "Mayor precio",
    },
  ],
  filters: [],
  available_filters: [
    {
      id: "official_store",
      name: "Tiendas oficiales",
      type: "text",
      values: [
        {
          id: "all",
          name: "Todas las tiendas oficiales",
          results: 4094,
        },
        {
          id: "76622",
          name: "GMP",
          results: 40,
        },
        {
          id: "2553",
          name: "Kadur",
          results: 705,
        },
        {
          id: "1839",
          name: "Kossok Powersports",
          results: 39,
        },
        {
          id: "2381",
          name: "Outlet Deportivo Oficial",
          results: 92,
        },
        {
          id: "2696",
          name: "DeporAr",
          results: 65,
        },
        {
          id: "2678",
          name: "SOLO DEPORTES",
          results: 47,
        },
        {
          id: "58244",
          name: "MUNICH SPORTS",
          results: 38,
        },
        {
          id: "1246",
          name: "PUMA",
          results: 55,
        },
        {
          id: "2269",
          name: "Kaddy Golf",
          results: 55,
        },
        {
          id: "2087",
          name: "Punto Deportivo",
          results: 46,
        },
        {
          id: "1450",
          name: "Nike",
          results: 19,
        },
        {
          id: "52435",
          name: "MALLOY SPORTS",
          results: 19,
        },
        {
          id: "2859",
          name: "CRAFTERS",
          results: 10,
        },
        {
          id: "70",
          name: "Jugueteria Carrousel",
          results: 10,
        },
        {
          id: "3027",
          name: "Sorma",
          results: 1,
        },
      ],
    },
    {
      id: "discount",
      name: "Descuentos",
      type: "number",
      values: [
        {
          id: "5-100",
          name: "Desde 5% OFF",
          results: 7867,
        },
        {
          id: "10-100",
          name: "Desde 10% OFF",
          results: 4304,
        },
        {
          id: "15-100",
          name: "Desde 15% OFF",
          results: 2656,
        },
        {
          id: "20-100",
          name: "Desde 20% OFF",
          results: 2141,
        },
        {
          id: "25-100",
          name: "Desde 25% OFF",
          results: 752,
        },
        {
          id: "30-100",
          name: "Desde 30% OFF",
          results: 571,
        },
        {
          id: "40-100",
          name: "Desde 40% OFF",
          results: 156,
        },
        {
          id: "50-100",
          name: "Desde 50% OFF",
          results: 38,
        },
        {
          id: "60-100",
          name: "Desde 60% OFF",
          results: 9,
        },
      ],
    },
    {
      id: "price",
      name: "Precio",
      type: "range",
      values: [
        {
          id: "*-10000.0",
          name: "Hasta $ 10.000",
          results: 10681,
        },
        {
          id: "10000.0-35000.0",
          name: "$10.000 a $35.000",
          results: 16657,
        },
        {
          id: "35000.0-*",
          name: "Más de $35.000",
          results: 14801,
        },
      ],
    },
    {
      id: "accepts_mercadopago",
      name: "Filtro por MercadoPago",
      type: "boolean",
      values: [
        {
          id: "yes",
          name: "Con MercadoPago",
          results: 42139,
        },
      ],
    },
    {
      id: "installments",
      name: "Financiación",
      type: "text",
      values: [
        {
          id: "yes",
          name: "En cuotas",
          results: 40699,
        },
        {
          id: "no_interest",
          name: "Sin interés",
          results: 5451,
        },
        {
          id: "campaign_cuota_simple",
          name: "Cuota Simple",
          results: 122,
        },
      ],
    },
    {
      id: "shipping",
      name: "Envío",
      type: "text",
      values: [
        {
          id: "mercadoenvios",
          name: "Mercado Envíos",
          results: 40384,
        },
        {
          id: "fulfillment",
          name: "Full",
          results: 630,
        },
      ],
    },
    {
      id: "power_seller",
      name: "Filtro por calidad de vendedores",
      type: "boolean",
      values: [
        {
          id: "yes",
          name: "Mejores vendedores",
          results: 30276,
        },
      ],
    },
    {
      id: "since",
      name: "Filtro por fecha de comienzo",
      type: "text",
      values: [
        {
          id: "today",
          name: "Publicados hoy",
          results: 145,
        },
      ],
    },
    {
      id: "until",
      name: "Filtro por fecha de finalización",
      type: "text",
      values: [
        {
          id: "today",
          name: "Finalizan hoy",
          results: 9,
        },
      ],
    },
    {
      id: "has_video",
      name: "Filtro por publicaciones con video",
      type: "boolean",
      values: [
        {
          id: "yes",
          name: "Publicaciones con video",
          results: 3790,
        },
      ],
    },
    {
      id: "has_pictures",
      name: "Filtro por publicaciones con imágenes",
      type: "boolean",
      values: [
        {
          id: "yes",
          name: "Con fotos",
          results: 42139,
        },
      ],
    },
    {
      id: "adult_content",
      name: "Filtro de contenido adulto",
      type: "boolean",
      values: [
        {
          id: "yes",
          name: "Contenido adulto",
          results: 32,
        },
      ],
    },
    {
      id: "all_payment_methods_discount",
      name: "Descuentos para todos los medios de pago",
      type: "number",
      values: [
        {
          id: "5-100",
          name: "Desde 5% OFF",
          results: 789,
        },
        {
          id: "10-100",
          name: "Desde 10% OFF",
          results: 753,
        },
        {
          id: "15-100",
          name: "Desde 15% OFF",
          results: 167,
        },
        {
          id: "20-100",
          name: "Desde 20% OFF",
          results: 140,
        },
        {
          id: "30-100",
          name: "Desde 30% OFF",
          results: 72,
        },
      ],
    },
    {
      id: "price_campaign_id",
      name: "Campaña",
      type: "number",
      values: [
        {
          id: "MLA55008",
          name: "MLA55008",
          results: 9,
        },
        {
          id: "P-MLA14105460",
          name: "P-MLA14105460",
          results: 5,
        },
        {
          id: "MLA54082",
          name: "MLA54082",
          results: 4,
        },
        {
          id: "MLA54909",
          name: "MLA54909",
          results: 3,
        },
        {
          id: "P-MLA14105466",
          name: "P-MLA14105466",
          results: 1,
        },
        {
          id: "P-MLA14123358",
          name: "P-MLA14123358",
          results: 1,
        },
        {
          id: "P-MLA14105468",
          name: "P-MLA14105468",
          results: 1,
        },
        {
          id: "MLA55209",
          name: "MLA55209",
          results: 1,
        },
      ],
    },
    {
      id: "promotion_type",
      name: "Tipo de promoción",
      type: "text",
      values: [
        {
          id: "deal_of_the_day",
          name: "Oferta del día",
          results: 27,
        },
        {
          id: "lightning",
          name: "Oferta relámpago",
          results: 1,
        },
      ],
    },
    {
      id: "shipping_cost",
      name: "Costo de envío",
      type: "text",
      values: [
        {
          id: "free",
          name: "Gratis",
          results: 17833,
        },
      ],
    },
    {
      id: "category",
      name: "Categorías",
      type: "text",
      values: [
        {
          id: "MLA1285",
          name: "Fútbol",
          results: 6372,
        },
        {
          id: "MLA1338",
          name: "Fitness y Musculación",
          results: 2585,
        },
        {
          id: "MLA1132",
          name: "Juegos y Juguetes",
          results: 8497,
        },
        {
          id: "MLA1071",
          name: "Animales y Mascotas",
          results: 3776,
        },
        {
          id: "MLA1574",
          name: "Hogar, Muebles y Jardín",
          results: 2989,
        },
        {
          id: "MLA1322",
          name: "Tenis, Pádel y Squash",
          results: 2769,
        },
        {
          id: "MLA1309",
          name: "Básquet",
          results: 2514,
        },
        {
          id: "MLA4697",
          name: "Juegos de Salón",
          results: 2106,
        },
        {
          id: "MLA8959",
          name: "Pilates y Yoga",
          results: 1937,
        },
        {
          id: "MLA1384",
          name: "Bebés",
          results: 1674,
        },
        {
          id: "MLA1430",
          name: "Ropa y Accesorios",
          results: 1658,
        },
        {
          id: "MLA1333",
          name: "Voley",
          results: 1588,
        },
        {
          id: "MLA3025",
          name: "Libros, Revistas y Comics",
          results: 1404,
        },
        {
          id: "MLA9304",
          name: "Souvenirs, Cotillón y Fiestas",
          results: 1341,
        },
        {
          id: "MLA1342",
          name: "Golf",
          results: 1045,
        },
        {
          id: "MLA1292",
          name: "Ciclismo",
          results: 911,
        },
        {
          id: "MLA37856",
          name: "Handball",
          results: 612,
        },
        {
          id: "MLA3731",
          name: "Rugby",
          results: 612,
        },
        {
          id: "MLA3937",
          name: "Joyas y Relojes",
          results: 531,
        },
        {
          id: "MLA1168",
          name: "Música, Películas y Series",
          results: 414,
        },
        {
          id: "MLA409431",
          name: "Salud y Equipamiento Médico",
          results: 414,
        },
        {
          id: "MLA18369",
          name: "Softball y Beisbol",
          results: 396,
        },
        {
          id: "MLA1499",
          name: "Industrias y Oficinas",
          results: 387,
        },
        {
          id: "MLA1367",
          name: "Antigüedades y Colecciones",
          results: 306,
        },
        {
          id: "MLA1368",
          name: "Arte, Librería y Mercería",
          results: 279,
        },
        {
          id: "MLA5725",
          name: "Accesorios para Vehículos",
          results: 208,
        },
        {
          id: "MLA1362",
          name: "Camping, Caza y Pesca",
          results: 162,
        },
        {
          id: "MLA1144",
          name: "Consolas y Videojuegos",
          results: 162,
        },
        {
          id: "MLA1648",
          name: "Computación",
          results: 108,
        },
        {
          id: "MLA1302",
          name: "Fútbol Americano",
          results: 99,
        },
        {
          id: "MLA1403",
          name: "Alimentos y Bebidas",
          results: 90,
        },
        {
          id: "MLA3732",
          name: "Hockey",
          results: 90,
        },
        {
          id: "MLA438178",
          name: "Suplementos y Shakers",
          results: 72,
        },
        {
          id: "MLA2480",
          name: "Artes Marciales y Boxeo",
          results: 54,
        },
        {
          id: "MLA1000",
          name: "Electrónica, Audio y Video",
          results: 36,
        },
        {
          id: "MLA407134",
          name: "Herramientas",
          results: 27,
        },
        {
          id: "MLA416831",
          name: "Bádminton",
          results: 18,
        },
        {
          id: "MLA1051",
          name: "Celulares y Teléfonos",
          results: 18,
        },
        {
          id: "MLA5726",
          name: "Electrodomésticos y Aires Ac.",
          results: 18,
        },
        {
          id: "MLA1295",
          name: "Patín y Skateboard",
          results: 18,
        },
        {
          id: "MLA1512",
          name: "Agro",
          results: 9,
        },
        {
          id: "MLA1279",
          name: "Buceo",
          results: 9,
        },
        {
          id: "MLA1500",
          name: "Construcción",
          results: 9,
        },
        {
          id: "MLA1349",
          name: "Equitación y Polo",
          results: 9,
        },
        {
          id: "MLA1182",
          name: "Instrumentos Musicales",
          results: 9,
        },
        {
          id: "MLA1358",
          name: "Otros",
          results: 9,
        },
      ],
    },
    {
      id: "state",
      name: "Ubicación",
      type: "text",
      values: [
        {
          id: "TUxBUENBUGw3M2E1",
          name: "Capital Federal",
          results: 22092,
        },
        {
          id: "TUxBUEdSQXJlMDNm",
          name: "Bs.As. G.B.A. Sur",
          results: 4934,
        },
        {
          id: "TUxBUEdSQWVmNTVm",
          name: "Bs.As. G.B.A. Oeste",
          results: 4388,
        },
        {
          id: "TUxBUEdSQWU4ZDkz",
          name: "Bs.As. G.B.A. Norte",
          results: 4318,
        },
        {
          id: "TUxBUENPUmFkZGIw",
          name: "Córdoba",
          results: 1575,
        },
        {
          id: "TUxBUFNBTmU5Nzk2",
          name: "Santa Fe",
          results: 992,
        },
        {
          id: "TUxBUFpPTmFpbnRl",
          name: "Buenos Aires Interior",
          results: 675,
        },
        {
          id: "TUxBUENPU2ExMmFkMw",
          name: "Bs.As. Costa Atlántica",
          results: 567,
        },
        {
          id: "TUxBUENIVXQxNDM1MQ",
          name: "Chubut",
          results: 297,
        },
        {
          id: "TUxBUE1FTmE5OWQ4",
          name: "Mendoza",
          results: 200,
        },
        {
          id: "TUxBUEVOVHMzNTdm",
          name: "Entre Ríos",
          results: 108,
        },
        {
          id: "TUxBUENIQW8xMTNhOA",
          name: "Chaco",
          results: 100,
        },
        {
          id: "TUxBUFRVQ244NmM3",
          name: "Tucumán",
          results: 81,
        },
        {
          id: "TUxBUFLNT29iZmZm",
          name: "Río Negro",
          results: 72,
        },
        {
          id: "TUxBUFNBTm9lOTlk",
          name: "Santiago del Estero",
          results: 72,
        },
        {
          id: "TUxBUEZPUmE1OTk5",
          name: "Formosa",
          results: 45,
        },
        {
          id: "TUxBUEpVSnk3YmUz",
          name: "Jujuy",
          results: 45,
        },
        {
          id: "TUxBUFNBTm5lYjU4",
          name: "San Juan",
          results: 36,
        },
        {
          id: "TUxBUFNBTnM0ZTcz",
          name: "San Luis",
          results: 36,
        },
        {
          id: "TUxBUFNBTno3ZmY5",
          name: "Santa Cruz",
          results: 27,
        },
        {
          id: "TUxBUE1JU3MzNjIx",
          name: "Misiones",
          results: 18,
        },
        {
          id: "TUxBUENBVGFiY2Fm",
          name: "Catamarca",
          results: 18,
        },
        {
          id: "TUxBUExBWmEyNzY0",
          name: "La Rioja",
          results: 18,
        },
        {
          id: "TUxBUFNBTGFjMTJi",
          name: "Salta",
          results: 18,
        },
        {
          id: "TUxBUE5FVW4xMzMzNQ",
          name: "Neuquén",
          results: 9,
        },
        {
          id: "TUxBUENPUnM5MjI0",
          name: "Corrientes",
          results: 9,
        },
      ],
    },
    {
      id: "BRAND",
      name: "Marca",
      type: "STRING",
      values: [
        {
          id: "276243",
          name: "Genérica",
          results: 1440,
        },
        {
          id: "120046",
          name: "Bestway",
          results: 936,
        },
        {
          id: "16031",
          name: "Wilson",
          results: 808,
        },
        {
          id: "3040570",
          name: "Striker",
          results: 592,
        },
        {
          id: "3106226",
          name: "Dribbling",
          results: 576,
        },
        {
          id: "764388",
          name: "Faydi",
          results: 560,
        },
        {
          id: "526510",
          name: "Munich",
          results: 472,
        },
        {
          id: "3040564",
          name: "Nassau",
          results: 440,
        },
        {
          id: "510488",
          name: "Penn",
          results: 408,
        },
        {
          id: "4646225",
          name: "DRB",
          results: 400,
        },
        {
          id: "3118759",
          name: "TSP",
          results: 384,
        },
        {
          id: "3088197",
          name: "Molten",
          results: 304,
        },
        {
          id: "2786787",
          name: "Spalding",
          results: 288,
        },
        {
          id: "9269",
          name: "Dunlop",
          results: 280,
        },
        {
          id: "764384",
          name: "Ditoys",
          results: 280,
        },
        {
          id: "3757393",
          name: "Proyec",
          results: 256,
        },
        {
          id: "23132",
          name: "Puma",
          results: 248,
        },
        {
          id: "3621973",
          name: "Trixie",
          results: 240,
        },
        {
          id: "912204",
          name: "Mir",
          results: 224,
        },
        {
          id: "2981724",
          name: "Gilbert",
          results: 224,
        },
        {
          id: "973755",
          name: "Rondi",
          results: 200,
        },
        {
          id: "16263",
          name: "Head",
          results: 200,
        },
        {
          id: "415471",
          name: "Intex",
          results: 192,
        },
        {
          id: "3088207",
          name: "Goalty",
          results: 192,
        },
        {
          id: "7255193",
          name: "Estadio",
          results: 184,
        },
        {
          id: "4868616",
          name: "Kong",
          results: 184,
        },
        {
          id: "2122893",
          name: "Footy",
          results: 184,
        },
        {
          id: "522406",
          name: "Kossok",
          results: 176,
        },
        {
          id: "15149",
          name: "Callaway",
          results: 168,
        },
        {
          id: "12901931",
          name: "Macu",
          results: 168,
        },
        {
          id: "5377063",
          name: "Wolfi",
          results: 152,
        },
        {
          id: "3680193",
          name: "Phi Phi Toys",
          results: 152,
        },
        {
          id: "15877042",
          name: "Serabot",
          results: 152,
        },
        {
          id: "6100390",
          name: "Sorma",
          results: 144,
        },
        {
          id: "5632733",
          name: "Magna Store",
          results: 144,
        },
        {
          id: "415948",
          name: "Topper",
          results: 144,
        },
        {
          id: "4468185",
          name: "Zoomundo",
          results: 136,
        },
        {
          id: "16588590",
          name: "Tourmalhyn",
          results: 136,
        },
        {
          id: "4646222",
          name: "DYS",
          results: 120,
        },
        {
          id: "17161079",
          name: "Bestia Peluda",
          results: 120,
        },
        {
          id: "6874941",
          name: "Yo Sí Puedo",
          results: 112,
        },
        {
          id: "563",
          name: "Premium",
          results: 112,
        },
        {
          id: "415945",
          name: "Penalty",
          results: 112,
        },
        {
          id: "15410",
          name: "TaylorMade",
          results: 112,
        },
        {
          id: "14810",
          name: "adidas",
          results: 112,
        },
        {
          id: "935424",
          name: "El Duende Azul",
          results: 104,
        },
        {
          id: "4647091",
          name: "Donic Schildkrot",
          results: 104,
        },
        {
          id: "416077",
          name: "Sensei",
          results: 104,
        },
        {
          id: "34516160",
          name: "Lucky Twins",
          results: 104,
        },
        {
          id: "19172970",
          name: "Ez Life",
          results: 104,
        },
        {
          id: "4318948",
          name: "Quuz",
          results: 96,
        },
        {
          id: "19163408",
          name: "Mercadoflash",
          results: 96,
        },
        {
          id: "13371556",
          name: "China",
          results: 96,
        },
        {
          id: "12355441",
          name: "Odea",
          results: 96,
        },
        {
          id: "12253808",
          name: "Attesa",
          results: 96,
        },
        {
          id: "764355",
          name: "Bisonte",
          results: 88,
        },
        {
          id: "5271506",
          name: "Pets Plast",
          results: 88,
        },
        {
          id: "4613221",
          name: "GymTonic",
          results: 88,
        },
        {
          id: "4417947",
          name: "Sport",
          results: 88,
        },
        {
          id: "3597021",
          name: "Iplay",
          results: 88,
        },
        {
          id: "2786862",
          name: "Gold",
          results: 88,
        },
        {
          id: "2336439",
          name: "Duravit",
          results: 88,
        },
        {
          id: "15187",
          name: "Titleist",
          results: 88,
        },
        {
          id: "13789637",
          name: "Mar Cristal",
          results: 88,
        },
        {
          id: "4696448",
          name: "Sunflex",
          results: 80,
        },
        {
          id: "4657731",
          name: "Vulcanita",
          results: 80,
        },
        {
          id: "432054",
          name: "Kagiva",
          results: 80,
        },
        {
          id: "3656926",
          name: "Rigolleau",
          results: 80,
        },
        {
          id: "2965412",
          name: "Drial",
          results: 80,
        },
        {
          id: "2787044",
          name: "Samba",
          results: 80,
        },
        {
          id: "13923225",
          name: "Premium Import",
          results: 80,
        },
        {
          id: "3119774",
          name: "Odear",
          results: 72,
        },
        {
          id: "2749673",
          name: "Vegui",
          results: 72,
        },
        {
          id: "12902171",
          name: "Sebigus",
          results: 72,
        },
        {
          id: "1098750",
          name: "Bullpadel",
          results: 72,
        },
        {
          id: "7847334",
          name: "Oasis",
          results: 64,
        },
        {
          id: "47576",
          name: "Panini",
          results: 64,
        },
        {
          id: "4585454",
          name: "CanCat",
          results: 64,
        },
        {
          id: "3080134",
          name: "GMP",
          results: 64,
        },
        {
          id: "3057976",
          name: "Sonnos",
          results: 64,
        },
        {
          id: "2153571",
          name: "Tapimovil",
          results: 64,
        },
        {
          id: "19915248",
          name: "Petz",
          results: 64,
        },
        {
          id: "16595",
          name: "Babolat",
          results: 64,
        },
        {
          id: "16329",
          name: "Prince",
          results: 64,
        },
        {
          id: "13730193",
          name: "Unna",
          results: 64,
        },
        {
          id: "13497941",
          name: "Kadur",
          results: 64,
        },
        {
          id: "9188",
          name: "Reebok",
          results: 56,
        },
        {
          id: "6560276",
          name: "Colours",
          results: 56,
        },
        {
          id: "6533532",
          name: "Rascals",
          results: 56,
        },
        {
          id: "58597",
          name: "Dufour",
          results: 56,
        },
        {
          id: "4856064",
          name: "Energy Fit",
          results: 56,
        },
        {
          id: "4666122",
          name: "Giant Dragon",
          results: 56,
        },
        {
          id: "43878",
          name: "Truper",
          results: 56,
        },
        {
          id: "432047",
          name: "Mikasa",
          results: 56,
        },
        {
          id: "4274813",
          name: "Hygge",
          results: 56,
        },
        {
          id: "4220005",
          name: "Sports",
          results: 56,
        },
        {
          id: "3753023",
          name: "Mafer",
          results: 56,
        },
        {
          id: "35341288",
          name: "Atletic Services",
          results: 56,
        },
        {
          id: "3106222",
          name: "Pintier",
          results: 56,
        },
        {
          id: "27288797",
          name: "JOGU",
          results: 56,
        },
        {
          id: "2428707",
          name: "Bright Starts",
          results: 56,
        },
        {
          id: "2314357",
          name: "Juegos y Juguetes",
          results: 56,
        },
        {
          id: "20793033",
          name: "Terrapet",
          results: 56,
        },
        {
          id: "15877043",
          name: "Ternuritas",
          results: 56,
        },
        {
          id: "14671",
          name: "Nike",
          results: 56,
        },
        {
          id: "13349576",
          name: "Isakito",
          results: 56,
        },
        {
          id: "911027",
          name: "Fibro",
          results: 48,
        },
        {
          id: "6334943",
          name: "Turby Toy",
          results: 48,
        },
        {
          id: "6027562",
          name: "Caffaro",
          results: 48,
        },
        {
          id: "4930654",
          name: "Dream Sport",
          results: 48,
        },
        {
          id: "45025",
          name: "Dolphin",
          results: 48,
        },
        {
          id: "416064",
          name: "California",
          results: 48,
        },
        {
          id: "35914409",
          name: "Unica Sport",
          results: 48,
        },
        {
          id: "3456814",
          name: "TWS",
          results: 48,
        },
        {
          id: "185762",
          name: "Kingmax",
          results: 48,
        },
        {
          id: "15923675",
          name: "Manzana Cotillon",
          results: 48,
        },
        {
          id: "14422721",
          name: "Argentina",
          results: 48,
        },
        {
          id: "13229968",
          name: "DTS",
          results: 48,
        },
        {
          id: "97698",
          name: "HB",
          results: 40,
        },
        {
          id: "6527600",
          name: "Loska",
          results: 40,
        },
        {
          id: "6250012",
          name: "MIR Fitness",
          results: 40,
        },
        {
          id: "6099890",
          name: "Get Fit",
          results: 40,
        },
        {
          id: "4691784",
          name: "Cresko",
          results: 40,
        },
        {
          id: "4296546",
          name: "Zootec",
          results: 40,
        },
        {
          id: "3508178",
          name: "Hacker",
          results: 40,
        },
        {
          id: "29197905",
          name: "Madma",
          results: 40,
        },
        {
          id: "2786298",
          name: "Shine",
          results: 40,
        },
        {
          id: "2431294",
          name: "Aba Sport",
          results: 40,
        },
        {
          id: "19455819",
          name: "KRV",
          results: 40,
        },
        {
          id: "19345",
          name: "VTech",
          results: 40,
        },
        {
          id: "17096851",
          name: "Beto",
          results: 40,
        },
        {
          id: "15955867",
          name: "Metegol",
          results: 40,
        },
        {
          id: "13556822",
          name: "Catit",
          results: 40,
        },
        {
          id: "12937082",
          name: "Iko Shop",
          results: 40,
        },
        {
          id: "12919747",
          name: "Dijes Comar",
          results: 40,
        },
        {
          id: "12098486",
          name: "A&D",
          results: 40,
        },
        {
          id: "10339564",
          name: "Meiso",
          results: 40,
        },
        {
          id: "1013907",
          name: "Leopard",
          results: 40,
        },
        {
          id: "8683597",
          name: "Slime",
          results: 32,
        },
        {
          id: "7406827",
          name: "Donic",
          results: 32,
        },
        {
          id: "6863039",
          name: "Silboreventos",
          results: 32,
        },
        {
          id: "6027152",
          name: "Skora",
          results: 32,
        },
        {
          id: "5929477",
          name: "Citykids",
          results: 32,
        },
        {
          id: "5741329",
          name: "South",
          results: 32,
        },
        {
          id: "5570153",
          name: "Fitnesas",
          results: 32,
        },
        {
          id: "5442969",
          name: "Colores",
          results: 32,
        },
        {
          id: "5415999",
          name: "LMR",
          results: 32,
        },
        {
          id: "511135",
          name: "DC",
          results: 32,
        },
        {
          id: "4961436",
          name: "Sol o Sol Playa",
          results: 32,
        },
        {
          id: "4831299",
          name: "DeporAr",
          results: 32,
        },
        {
          id: "478830",
          name: "Sanremo",
          results: 32,
        },
        {
          id: "4377093",
          name: "Party Store",
          results: 32,
        },
        {
          id: "432049",
          name: "Stadium",
          results: 32,
        },
        {
          id: "4145533",
          name: "Rascat",
          results: 32,
        },
        {
          id: "410974",
          name: "Gadnic",
          results: 32,
        },
        {
          id: "33243",
          name: "Disney",
          results: 32,
        },
        {
          id: "3212344",
          name: "Tissus",
          results: 32,
        },
        {
          id: "2898428",
          name: "New Plast",
          results: 32,
        },
        {
          id: "2804265",
          name: "SM",
          results: 32,
        },
        {
          id: "2786357",
          name: "MV",
          results: 32,
        },
        {
          id: "2511145",
          name: "Bulit",
          results: 32,
        },
        {
          id: "2468844",
          name: "Rotoys",
          results: 32,
        },
        {
          id: "22630322",
          name: "Bppets",
          results: 32,
        },
        {
          id: "22499599",
          name: "Enfiestados",
          results: 32,
        },
        {
          id: "20860135",
          name: "Nagukids",
          results: 32,
        },
        {
          id: "20696685",
          name: "Chuckit!",
          results: 32,
        },
        {
          id: "20402169",
          name: "Pet Gravity",
          results: 32,
        },
        {
          id: "19625461",
          name: "Bella Charm",
          results: 32,
        },
        {
          id: "19163556",
          name: "Fave",
          results: 32,
        },
        {
          id: "17578139",
          name: "Welstar",
          results: 32,
        },
        {
          id: "17511327",
          name: "DD2",
          results: 32,
        },
        {
          id: "16683128",
          name: "Golazo",
          results: 32,
        },
        {
          id: "14946346",
          name: "Juegosol",
          results: 32,
        },
        {
          id: "13916231",
          name: "Europaris",
          results: 32,
        },
        {
          id: "13024629",
          name: "El Mundo del Juguete",
          results: 32,
        },
        {
          id: "119306",
          name: "OK Baby",
          results: 32,
        },
        {
          id: "5671572",
          name: "Spri",
          results: 24,
        },
        {
          id: "5594697",
          name: "Gaiam",
          results: 24,
        },
        {
          id: "5446150",
          name: "Doyen",
          results: 24,
        },
        {
          id: "5404431",
          name: "Sportcom",
          results: 24,
        },
        {
          id: "5327443",
          name: "JSB",
          results: 24,
        },
        {
          id: "5275865",
          name: "JW",
          results: 24,
        },
        {
          id: "492254",
          name: "Ranbak",
          results: 24,
        },
        {
          id: "4753201",
          name: "Fire Sport",
          results: 24,
        },
        {
          id: "4522682",
          name: "Tourna",
          results: 24,
        },
        {
          id: "4315280",
          name: "Durapet's",
          results: 24,
        },
        {
          id: "428660",
          name: "Diadora",
          results: 24,
        },
        {
          id: "410979",
          name: "Noga",
          results: 24,
        },
        {
          id: "3911258",
          name: "Cotillón Concept",
          results: 24,
        },
        {
          id: "3833187",
          name: "Trops",
          results: 24,
        },
        {
          id: "36837264",
          name: "Gymman",
          results: 24,
        },
        {
          id: "3639192",
          name: "Rawlings",
          results: 24,
        },
      ],
    },
    {
      id: "ITEM_CONDITION",
      name: "Condición",
      type: "STRING",
      values: [
        {
          id: "2230284",
          name: "Nuevo",
          results: 35720,
        },
        {
          id: "2230581",
          name: "Usado",
          results: 2376,
        },
      ],
    },
    {
      id: "SALE_FORMAT",
      name: "Formato de venta",
      type: "STRING",
      values: [
        {
          id: "1359391",
          name: "Unidad",
          results: 9976,
        },
        {
          id: "1359392",
          name: "Pack",
          results: 3200,
        },
      ],
    },
  ],
  pdp_tracking: {
    group: false,
    product_info: [
      {
        id: "MLA29095966",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA35649180",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA25749196",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA22073644",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA30342988",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA26194132",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA24388831",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA22907159",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA22726957",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA19775472",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA28810791",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA37239716",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA25977609",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA28869765",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA29542450",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA34755630",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA25845705",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA20959979",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA22073643",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA26986127",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA27566338",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA37887758",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA23575995",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA21848733",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA19777686",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA34956877",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA35247628",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA26320799",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA35574393",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA32953981",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA10151264",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA27237119",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA37135742",
        score: 1,
        status: "shown",
      },
      {
        id: "MLA21238648",
        score: 1,
        status: "shown",
      },
    ],
  },
  user_context: null,
};
const responseMockFetchItem = {
  id: "MLA1390220763",
  site_id: "MLA",
  title: "Pelota Fútbol No4 Profesional Futsal Medio Pique Cancha De 5",
  seller_id: 98002580,
  category_id: "MLA1287",
  official_store_id: null,
  price: 33603.38,
  base_price: 33603.38,
  original_price: 54199,
  currency_id: "ARS",
  initial_quantity: 278,
  sale_terms: [
    {
      id: "WARRANTY_TYPE",
      name: "Tipo de garantía",
      value_id: "6150835",
      value_name: "Sin garantía",
      value_struct: null,
      values: [
        {
          id: "6150835",
          name: "Sin garantía",
          struct: null,
        },
      ],
      value_type: "list",
    },
    {
      id: "INVOICE",
      name: "Facturación",
      value_id: "6891885",
      value_name: "Factura A",
      value_struct: null,
      values: [
        {
          id: "6891885",
          name: "Factura A",
          struct: null,
        },
      ],
      value_type: "list",
    },
  ],
  buying_mode: "buy_it_now",
  listing_type_id: "gold_special",
  condition: "new",
  permalink:
    "https://articulo.mercadolibre.com.ar/MLA-1390220763-pelota-futbol-no4-profesional-futsal-medio-pique-cancha-de-5-_JM",
  thumbnail_id: "753540-MLA74782661379_022024",
  thumbnail: "http://http2.mlstatic.com/D_753540-MLA74782661379_022024-I.jpg",
  pictures: [
    {
      id: "753540-MLA74782661379_022024",
      url: "http://http2.mlstatic.com/D_753540-MLA74782661379_022024-O.jpg",
      secure_url:
        "https://http2.mlstatic.com/D_753540-MLA74782661379_022024-O.jpg",
      size: "500x494",
      max_size: "939x929",
      quality: "",
    },
    {
      id: "982363-MLA71108172266_082023",
      url: "http://http2.mlstatic.com/D_982363-MLA71108172266_082023-O.jpg",
      secure_url:
        "https://http2.mlstatic.com/D_982363-MLA71108172266_082023-O.jpg",
      size: "375x500",
      max_size: "900x1200",
      quality: "",
    },
    {
      id: "858073-MLA74781178263_022024",
      url: "http://http2.mlstatic.com/D_858073-MLA74781178263_022024-O.jpg",
      secure_url:
        "https://http2.mlstatic.com/D_858073-MLA74781178263_022024-O.jpg",
      size: "497x500",
      max_size: "936x940",
      quality: "",
    },
    {
      id: "995882-MLU72654412751_112023",
      url: "http://http2.mlstatic.com/D_995882-MLU72654412751_112023-O.jpg",
      secure_url:
        "https://http2.mlstatic.com/D_995882-MLU72654412751_112023-O.jpg",
      size: "500x319",
      max_size: "960x614",
      quality: "",
    },
    {
      id: "682538-MLU72654412767_112023",
      url: "http://http2.mlstatic.com/D_682538-MLU72654412767_112023-O.jpg",
      secure_url:
        "https://http2.mlstatic.com/D_682538-MLU72654412767_112023-O.jpg",
      size: "500x333",
      max_size: "959x640",
      quality: "",
    },
    {
      id: "697580-MLU72654164467_112023",
      url: "http://http2.mlstatic.com/D_697580-MLU72654164467_112023-O.jpg",
      secure_url:
        "https://http2.mlstatic.com/D_697580-MLU72654164467_112023-O.jpg",
      size: "420x500",
      max_size: "903x1075",
      quality: "",
    },
    {
      id: "924398-MLU73214200081_122023",
      url: "http://http2.mlstatic.com/D_924398-MLU73214200081_122023-O.jpg",
      secure_url:
        "https://http2.mlstatic.com/D_924398-MLU73214200081_122023-O.jpg",
      size: "494x500",
      max_size: "494x500",
      quality: "",
    },
    {
      id: "709917-MLU73214200089_122023",
      url: "http://http2.mlstatic.com/D_709917-MLU73214200089_122023-O.jpg",
      secure_url:
        "https://http2.mlstatic.com/D_709917-MLU73214200089_122023-O.jpg",
      size: "494x500",
      max_size: "494x500",
      quality: "",
    },
  ],
  video_id: null,
  descriptions: [],
  accepts_mercadopago: true,
  non_mercado_pago_payment_methods: [],
  shipping: {
    mode: "me2",
    methods: [],
    tags: ["mandatory_free_shipping"],
    dimensions: null,
    local_pick_up: false,
    free_shipping: true,
    logistic_type: "fulfillment",
    store_pick_up: false,
  },
  international_delivery_mode: "none",
  seller_address: {
    city: {
      name: "Dorrego",
    },
    state: {
      id: "AR-M",
      name: "Mendoza",
    },
    country: {
      id: "AR",
      name: "Argentina",
    },
    search_location: {
      neighborhood: {
        id: "TUxBQkdVQTEyMzRa",
        name: "Guaymallén",
      },
      city: {
        id: "TUxBQ0dVQTI0Yjcw",
        name: "Guaymallén",
      },
      state: {
        id: "TUxBUE1FTmE5OWQ4",
        name: "Mendoza",
      },
    },
    id: 192127241,
  },
  seller_contact: null,
  location: {},
  coverage_areas: [],
  attributes: [
    {
      id: "BALL_SIZE",
      name: "Tamaño de la pelota",
      value_id: "3040573",
      value_name: "4",
      values: [
        {
          id: "3040573",
          name: "4",
          struct: null,
        },
      ],
      value_type: "number",
    },
    {
      id: "BLADDER_MATERIAL",
      name: "Material de la cámara",
      value_id: "432093",
      value_name: "Butilo",
      values: [
        {
          id: "432093",
          name: "Butilo",
          struct: null,
        },
      ],
      value_type: "string",
    },
    {
      id: "BRAND",
      name: "Marca",
      value_id: "45025",
      value_name: "Dolphin",
      values: [
        {
          id: "45025",
          name: "Dolphin",
          struct: null,
        },
      ],
      value_type: "string",
    },
    {
      id: "COLOR",
      name: "Color",
      value_id: "52000",
      value_name: "Naranja",
      values: [
        {
          id: "52000",
          name: "Naranja",
          struct: null,
        },
      ],
      value_type: "string",
    },
    {
      id: "COMPETITION",
      name: "Competencia",
      value_id: "13456237",
      value_name: "Nassau",
      values: [
        {
          id: "13456237",
          name: "Nassau",
          struct: null,
        },
      ],
      value_type: "string",
    },
    {
      id: "EMPTY_GTIN_REASON",
      name: "Motivo de GTIN vacío",
      value_id: "17055160",
      value_name: "El producto no tiene código registrado",
      values: [
        {
          id: "17055160",
          name: "El producto no tiene código registrado",
          struct: null,
        },
      ],
      value_type: "list",
    },
    {
      id: "EXTERNAL_MATERIALS",
      name: "Materiales externos",
      value_id: "22059964",
      value_name: "Poliuretano tramado",
      values: [
        {
          id: "22059964",
          name: "Poliuretano tramado",
          struct: null,
        },
      ],
      value_type: "string",
    },
    {
      id: "FOOTBALL_BALL_CIRCUMFERENCE",
      name: "Circunferencia",
      value_id: "19780808",
      value_name: "63cm",
      values: [
        {
          id: "19780808",
          name: "63cm",
          struct: null,
        },
      ],
      value_type: "string",
    },
    {
      id: "GROUND_TYPES",
      name: "Tipos de superficie",
      value_id: null,
      value_name: "Cemento,Césped artificial,Pasto sintético",
      values: [
        {
          id: "7101956",
          name: "Cemento",
          struct: null,
        },
        {
          id: "428665",
          name: "Césped artificial",
          struct: null,
        },
        {
          id: "18501661",
          name: "Pasto sintético",
          struct: null,
        },
      ],
      value_type: "string",
    },
    {
      id: "GTIN",
      name: "Código universal de producto",
      value_id: "-1",
      value_name: null,
      values: [
        {
          id: "-1",
          name: null,
          struct: null,
        },
      ],
      value_type: "string",
    },
    {
      id: "IS_A_MINIBALL",
      name: "Es una minipelota",
      value_id: "242084",
      value_name: "No",
      values: [
        {
          id: "242084",
          name: "No",
          struct: null,
        },
      ],
      value_type: "boolean",
    },
    {
      id: "ITEM_CONDITION",
      name: "Condición del ítem",
      value_id: "2230284",
      value_name: "Nuevo",
      values: [
        {
          id: "2230284",
          name: "Nuevo",
          struct: null,
        },
      ],
      value_type: "list",
    },
    {
      id: "LEAGUE",
      name: "Liga",
      value_id: "13456242",
      value_name: "Futbol 5",
      values: [
        {
          id: "13456242",
          name: "Futbol 5",
          struct: null,
        },
      ],
      value_type: "string",
    },
    {
      id: "MAIN_COLOR",
      name: "Color principal",
      value_id: "2450327",
      value_name: "Naranja",
      values: [
        {
          id: "2450327",
          name: "Naranja",
          struct: null,
        },
      ],
      value_type: "list",
    },
    {
      id: "MIN_RECOMMENDED_AGE",
      name: "Edad mínima recomendada",
      value_id: "3971030",
      value_name: "0 años",
      values: [
        {
          id: "3971030",
          name: "0 años",
          struct: {
            number: 0,
            unit: "años",
          },
        },
      ],
      value_type: "number_unit",
    },
    {
      id: "MODEL",
      name: "Modelo",
      value_id: "65385",
      value_name: "Cobra",
      values: [
        {
          id: "65385",
          name: "Cobra",
          struct: null,
        },
      ],
      value_type: "string",
    },
    {
      id: "PRODUCT_FEATURES",
      name: "Características del producto",
      value_id: "8847339",
      value_name: "Sin vencimiento",
      values: [
        {
          id: "8847339",
          name: "Sin vencimiento",
          struct: null,
        },
      ],
      value_type: "list",
    },
    {
      id: "RECOMMENDED_USES",
      name: "Usos recomendados",
      value_id: null,
      value_name: "Cemento,Pasto Sintético,Piso flotante",
      values: [
        {
          id: "6676209",
          name: "Cemento",
          struct: null,
        },
        {
          id: "22059961",
          name: "Pasto Sintético",
          struct: null,
        },
        {
          id: "22059962",
          name: "Piso flotante",
          struct: null,
        },
      ],
      value_type: "string",
    },
    {
      id: "RELEASE_YEAR",
      name: "Año de lanzamiento",
      value_id: "2289621",
      value_name: "2018",
      values: [
        {
          id: "2289621",
          name: "2018",
          struct: null,
        },
      ],
      value_type: "number",
    },
    {
      id: "SALE_FORMAT",
      name: "Formato de venta",
      value_id: "1359391",
      value_name: "Unidad",
      values: [
        {
          id: "1359391",
          name: "Unidad",
          struct: null,
        },
      ],
      value_type: "list",
    },
    {
      id: "SEAM_TYPE",
      name: "Tipo de costura",
      value_id: "2469720",
      value_name: "Cosida a mano",
      values: [
        {
          id: "2469720",
          name: "Cosida a mano",
          struct: null,
        },
      ],
      value_type: "string",
    },
    {
      id: "SELLER_SKU",
      name: "SKU",
      value_id: null,
      value_name: "pelota dolphin n4",
      values: [
        {
          id: null,
          name: "pelota dolphin n4",
          struct: null,
        },
      ],
      value_type: "string",
    },
    {
      id: "SHIPMENT_PACKING",
      name: "Embalaje del envío",
      value_id: "7435891",
      value_name: "Bolsa",
      values: [
        {
          id: "7435891",
          name: "Bolsa",
          struct: null,
        },
      ],
      value_type: "list",
    },
    {
      id: "UNITS_PER_PACK",
      name: "Unidades por pack",
      value_id: "2726554",
      value_name: "1",
      values: [
        {
          id: "2726554",
          name: "1",
          struct: null,
        },
      ],
      value_type: "number",
    },
  ],
  listing_source: "",
  variations: [],
  status: "active",
  sub_status: [],
  tags: [
    "certified_quality_thumbnail",
    "good_quality_thumbnail",
    "immediate_payment",
    "cart_eligible",
  ],
  warranty: "Sin garantía",
  catalog_product_id: "MLA19868803",
  domain_id: "MLA-FOOTBALL_BALLS",
  parent_item_id: null,
  deal_ids: ["MLA54082"],
  automatic_relist: false,
  date_created: "2023-09-27T16:59:29.000Z",
  last_updated: "2024-07-17T15:55:13.000Z",
  health: null,
  catalog_listing: true,
};
const responseMockFetchItemDescription = {
  text: "",
  plain_text:
    "Encontrá en el COBRA la calidad e innovación que Dolphin puede brindar. Disfrutá de tus momentos de entrenamiento y juego, así como de dispersión, con una pelota que es ideal para vos.",
  last_updated: "2023-09-27T16:59:34.077Z",
  date_created: "2023-09-27T16:59:34.077Z",
  snapshot: {
    url: "http://descriptions.mlstatic.com/D-MLA1390220763.jpg?hash=8520c3b8559cb08aa7e782b8f5334ffe_0x0",
    width: 0,
    height: 0,
    status: "",
  },
};
const responseMockFetchItemsEmpty = {
    site_id: "MLA",
    country_default_time_zone: "GMT-03:00",
    query: "pelotaeqweqwqweweqeqweqwqweqweqwe",
    paging: {
      total: 0,
      primary_results: 0,
      offset: 0,
      limit: 50,
    },
    results: [],
    sort: {
      id: "relevance",
      name: "Más relevantes",
    },
    available_sorts: [
      {
        id: "price_asc",
        name: "Menor precio",
      },
      {
        id: "price_desc",
        name: "Mayor precio",
      },
    ],
    filters: [],
    available_filters: [],
    pdp_tracking: {
      group: false,
      product_info: [],
    },
    user_context: null,
  };
const searchParamsDto = {
  q: "pelota",
  author: {
    name: "Juan",
    lastname: "Herrera",
  },
};
const getByIdDto = {
  idItem: "MLA1390220763",
  author: {
    name: "Juan",
    lastname: "Herrera",
  },
};
module.exports = {
  responseMockFetchItems,
  responseMockFetchItem,
  responseMockFetchItemDescription,
  searchParamsDto,
  getByIdDto,
  responseMockFetchItemsEmpty,
};
